version: '3'

services:

  grants-db:
    image: postgres:15-alpine
    container_name: grants-db
    command: postgres -c "log_lock_waits=on" -N 1000 -c "fsync=off"
    env_file: ./local.env
    ports:
      - "5432:5432"
    volumes:
      - grantsdbdata:/var/lib/postgresql/data

  grants-api:
    build:
      context: .
      target: dev
      args:
        - RUN_UID=${RUN_UID:-4000}
        - RUN_USER=${RUN_USER:-api}
    command: ["poetry", "run", "flask", "--app", "src.app", "run", "--host", "0.0.0.0", "--port", "8080", "--reload"]
    container_name: grants-api
    env_file: ./local.env
    ports:
      - 8080:8080
    volumes:
      - .:/api
    depends_on:
      - grants-db

volumes:
  grantsdbdata:
